version: '2'
services:
    contact-app:
        image: contact
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://contact-postgresql:5432/contact
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    contact-postgresql:
        extends:
            file: postgresql.yml
            service: contact-postgresql
